### ISSUE TITLE
Publish never resolves if error occured

### ISSUE THREAD

**Issue by morigs** [benbria/node-amqp-connection-manager#124]
For example, when I'm trying to publish to nonexistent exchange, channel is closing by broker (so it becomes `null` in channel wrapper). And then channel wrapper r[eturns message back to the queue](https://github.com/benbria/node-amqp-connection-manager/blob/6b512e8a84453ea8ff860bc0f3ce8615000f005a/src/ChannelWrapper.js#L380). Because underlying connection isn't closed message stays at queue forever. And even after reconnect channel wrapper is trying to send this message and channel becomes closed again.
I think this is critical issue. It's better to reject messages sent to closed channel

**Comment by SSANSH** [comment]
+1

**Comment by SSANSH** [comment]
if I propose an MR as explaine by morigs, Do you think I have any chance that this will be merge.
I am agree with morigs, this is a critical issue and server stay on bad state.
for information I reproduce this issue with this kind of error:
Connection closed: 501 (FRAME-ERROR) with message "FRAME_ERROR - type 2, all octets = <<>>: {frame_too_large,4532,4088}

**Comment by SSANSH** [comment]
is it already an active project? or the project is it dead?

**Comment by rarg** [comment]
Hello @jwalton are you still maintaining this project ?

**Comment by jwalton** [comment]
Yeah, I'm still here.  :)

And yes, I'd welcome a PR.

**Comment by SSANSH** [comment]
Please comment my PR https://github.com/benbria/node-amqp-connection-manager/pull/134

**Comment by jwalton** [comment]
Fixed by: #134
