### ISSUE TITLE
Need to add json to options when creating channel?

### ISSUE THREAD

**Issue by petermorlion** [benbria/node-amqp-connection-manager#15]
When calling `sendToQueue` as in the readme:

    channelWrapper.sendToQueue('rxQueueName', {hello: 'World'})

I'm getting an error:

    TypeError: content is not a buffer

When I use this:

    channelWrapper.sendToQueue('rxQueueName', new Buffer(JSON.stringify({hello: 'World'}), {contentType: 'application/json'}))

It seems to work fine.

The [amqplib docs](http://www.squaremobius.net/amqp.node/channel_api.html#channel_sendToQueue) mention a buffer too. I noticed you do this in ChannelWrapper based on the `options.json` flag, but that option never seems to be set, unless I change this:

```
var channelWrapper = connection.createChannel({
    setup: function(channel) {
        // `channel` here is a regular amqplib `ConfirmChannel`.
            return channel.assertQueue('rxQueueName', {durable: true})
        }
      });
```

to this:

```
var channelWrapper = connection.createChannel({
    setup: function(channel) {
        // `channel` here is a regular amqplib `ConfirmChannel`.
            return channel.assertQueue('rxQueueName', {durable: true})
        },
        json: true // added this
      });
```

**Comment by jwalton** [comment]
Yes sir, the readme example appears to be broken.

**Comment by jwalton** [comment]
Fixed the README.md.  :)
