### ISSUE TITLE
New version has error in connection

### ISSUE THREAD

**Issue by AminAlizadeh-m** [benbria/node-amqp-connection-manager#172]
Hi
About 6 hours ago, when the new version was published, I had a connection problem.
And the RabbitMQ connection is automatically disconnected!
error status code is 406
Closing Channels

**Comment by TrejGun** [comment]
@jwalton hey hey

I was able to reproduce the bug using my repo, it was actually always there, you just did not get the point and did not call the URL to invoke the request. So here is an explanation:

NestJS uses two types of requests, `emit` - the one which sends the message and forgets about it, `send` - the one which waits for the response. The bug is only in the second one. That's why you were not able to reproduce the bug with https://github.com/rengthp/nestjs-rabbitmq-microservice/blob/master/microservice-client/src/app.controller.ts

pls ping me if you need more assistance

**Comment by TrejGun** [comment]
@jwalton can we give this a go?

**Comment by jwalton** [comment]
Hey Trej.  I’ll have a look at this… soon.  My mom passed away very unexpectedly and without any warning a week ago.  I was supposed to be on vacation last week so I could take my daughter over to swim and play with her.  Instead I’m planning a funeral.  I’ll get back on this as soon as I can, but right now - as you can imagine - I… well… I have no words.

**Comment by TrejGun** [comment]
oh man, I'm so sorry

**Comment by kevin192291** [comment]
@TrejGun Hey, Have you attempted to call:
```
async onApplicationBootstrap() {
    await this.<Your ClientProxy Instance>.connect();
  }
```
?

**Comment by TrejGun** [comment]
no, I believe this is covered by the framework, there is only

```
 app.connectMicroservice<MicroserviceOptions>({
    transport: Transport.RMQ,
    options: {
      urls: [process.env.RMQ_URL],
      queue: process.env.RMQ_QUEUE,
    },
  });

  await app
    .startAllMicroservices()
```

**Comment by kevin192291** [comment]
> I believe this is covered by the framework, there is only
> 
> ```
>  app.connectMicroservice<MicroserviceOptions>({
>     transport: Transport.RMQ,
>     options: {
>       urls: [process.env.RMQ_URL],
>       queue: process.env.RMQ_QUEUE,
>     },
>   });
> 
>   await app
>     .startAllMicroservices()
> ```

It WAS, as of a recent release (i think v8) it is no longer connecting, and you must do it manually. It seems like regression to me, but I don't know if this was intended. That said, Try that out, at very least, try awaiting the connect right above your "SEND()" call. I suspect what you will see in your rabbitMQ management console is that BEFORE calling connect() you will NOT see a connection, then after, the connection will show up.

**Comment by TrejGun** [comment]
this happened after a major version update of nestjs .
in fact, it has happened between 3.3.0 and 3.4.0 of this lib.
anyways your suggestion does not work for me

```
@Module({
  controllers: [PotatoController],
  providers: [PotatoService],
  exports: [PotatoService],
})
export class PotatoModule {
  @Client({
    transport: Transport.RMQ,
    options: {
      urls: [process.env.RMQ_URL],
      queue: process.env.RMQ_QUEUE,
    },
  })
  client: ClientProxy;

  public async onApplicationBootstrap(): Promise<void> {
    console.log("!!!")
    await this.client.connect();
  }
}
```

you can check by yourself https://github.com/TrejGun/hot-potato-using-nestjs-microservices branch kevin192291 

I thought the order of sending the messages and subscribing to the reply queue has changed but I was not able to find evidence while writing this answer
