### ISSUE TITLE
reconnection retry interval

### ISSUE THREAD

**Issue by ralcini** [benbria/node-amqp-connection-manager#2]
Hi,

I think it could be very useful to specify a retry interval between reconnection attempts.
What are your thoughts on this point?

Regards

**Comment by jwalton** [comment]
Yeah, probably a good idea.  Right now it uses the heartbeat duration as the wait time, but it would probably be a good idea to make this independently configurable.

**Comment by jwalton** [comment]
Fixed in v1.1.0.  :)

**Comment by ralcini** [comment]
good! =)
