### ISSUE TITLE
Nonexistent drop event

### ISSUE THREAD

**Issue by polson136** [benbria/node-amqp-connection-manager#21]
In the documentation, it states that the drop event is  "called when a JSON message was dropped because it could not be encoded." I can't seem to produce this result (for logging purposes only), and when I look at the code there doesn't seem to be any code that fires it (I could be wrong, my coffeescript is nonexistent). What is the event actually supposed to do?

**Comment by jwalton** [comment]
I'm thinking at one point I planned to emit a drop event if [`JSON.stringify()`](https://github.com/benbria/node-amqp-connection-manager/blob/master/src/ChannelWrapper.coffee#L192) threw an error, but by the looks of things we just let that get turned into a plain old vanilla error.  :P
