### ISSUE TITLE
Support for per URL connection options

### ISSUE THREAD

**Issue by skaegi** [benbria/node-amqp-connection-manager#29]
Some of the connectionOptions we use are per URL (for example "servername" which boils down to TLSSocket.servername and used as part of the TLS Server Name Indication). Could `connect` be altered to accept an array of {url:... , options:...} or something along those lines.

**Comment by jwalton** [comment]
That definitely sounds like it could be done - make it so `urls` is either a list of strings, or a list of `{url, options}` or a mixed list?  I'd welcome a PR.  I just refactored this entire codebase from coffeescript to javascript, so it should be a little easier to contribute to now.  :)

**Comment by skaegi** [comment]
Thanks @jwalton -- sorry for the delay. I think I can look at doing this when I get a moment...

**Comment by skaegi** [comment]
@jwalton Here's the general idea -- https://github.com/benbria/node-amqp-connection-manager/pull/34
