### ISSUE TITLE
Publish a new version to npm

### ISSUE THREAD

**Issue by skaegi** [benbria/node-amqp-connection-manager#44]
Could you create a new release please.

**Comment by skaegi** [comment]
Is there anything that I could do to help here?

**Comment by jwalton** [comment]
Oops.  Sorry, I just saw this.  And I didn't realize your commits from June 4th didn't follow conventional commit, otherwise semantic-release would have published this already.  I'll go publish a release.  :)

**Comment by jwalton** [comment]
Release 2.1.0.
