### ISSUE TITLE
require works, but import does not

### ISSUE THREAD

**Issue by gwh-cpnet** [benbria/node-amqp-connection-manager#51]
regarding node-amqp-connection-manager@2.1.1, with babel-cli@6.26, babel-preset-node8@1.2.0

```js
const amqp = require('amqp-connection-manager');  
console.log(amqp);
```

run it with `babel-node`, it outputs:
```
{ connect: [Function: connect] }
```

but with `import` in ES6, amqp is undefined:
```js
import amqp from 'amqp-connection-manager';
console.log(amqp);
```
outputs:
```
undefined
```

well, other deps in my code works fine. node-amqp-connection-manager@1.3.7 works fine too.

**Comment by jwalton** [comment]
A casualty of me rewriting this, converting from coffee-script to ES6.  You can do this as a workaround:

```
import { connect } from 'amqp-connection-manager';
```

But I just committed a fix, so semantic-release should push a new build momentarily.

**Comment by gwh-cpnet** [comment]
It is fixed. Thank you for the right-away response.
