### ISSUE TITLE
channelwrapper.nackAll() is not function

### ISSUE THREAD

**Issue by mjet08** [benbria/node-amqp-connection-manager#60]
When i am adding the code `channelWrapper.nackAll()` then it gives me the error

0|app  | TypeError: channelWrapper.nackAll is not a function

So is there any way I can implement nackAll() function. Basically I am trying to put all the unacknowledged messages to the queue so that they can be recaptured.

**Comment by jwalton** [comment]
Fixed.  Enjoy!  (Semantic-release should publish a new release in a few moments...)
