### ISSUE TITLE
Cancel consumer

### ISSUE THREAD

**Issue by p-bakker** [benbria/node-amqp-connection-manager#63]
Hi,

Am using the AMQP Connection Manager in a micro service deployed in containers on Kubernetes. As K8s manages scaling and such it starts and stops containers at its own digression.

I'm trying to make it so that my MicroService shuts down gracefully, meaning that any inflight messages are properly handled, but the service isn't send new messages from RMQ.

AFAIK, in plain amqp I should basic.cancel the consumer, before calling .close() on the channel.

However, AMQP Connection Manager doesn't do this nor does it seem to allow me to do so. The .close() function on the ChannelWrapper doesn't do basic.cancel before the calling .close() on the channel.

I tried hacking it, by accessing the _channel property on the ChannelWrapper and calling .cancel() on it directly, but it seems this triggers auto reconnect by the AMQP Connection Manager.

Is my thinking flawed? Am I missing something? Or is this indeed not supported? If the later, could it be added or won't that work within the goals of the Connection Manager?

**Comment by jwalton** [comment]
> I tried hacking it, by accessing the _channel property on the ChannelWrapper and calling .cancel() on it directly, but it seems this triggers auto reconnect by the AMQP Connection Manager.

It's weird that `cancel()` causes the connection to drop, isn't it?  From reading the [docs](http://www.squaremobius.net/amqp.node/channel_api.html#channel_cancel) it doesn't seem like that should happen?  Or maybe the connection isn't dropping but we're getting an event from amqp that's making us try to reconnect anyways?  I'd be curious to know what's going on there...

Just off the top of my head, you could maybe call [removeSetup()](https://github.com/benbria/node-amqp-connection-manager#channelwrapperremovesetupsetup-teardown) with a teardown to call `cancel()` on your channel before you call `close()`.  That's a bit hacky.  :P

**Comment by jwalton** [comment]
If you can come up with a cleaner way to do this, I'd welcome a PR.  Maybe have a `onClose` option to `createChannel()` that gets called right before we destroy the channel?

**Comment by p-bakker** [comment]
tnx for the feedback, will do some fiddling and get back to you

**Comment by p-bakker** [comment]
Dunno what happened before, couldn't reproduce the reconnect behavior.

Managed to get what I need through your suggestion using the removeSetup() function
