### ISSUE TITLE
ConnectionManager.close doesn't close the connection

### ISSUE THREAD

**Issue by mrlannigan** [benbria/node-amqp-connection-manager#7]
I can't tell if it was intentional or not and I'm really just trying to understand. Why doesn't the ConnectionManager.close function not close the connection in addition to the channels?

If I would like to close the connection, I have to do this:

```
connectionManager._currentConnection.connection.close()
```

and it feels just dirty. :shower:

**Comment by jwalton** [comment]
It should close the channel.  -_-

-Jason

**Comment by mrlannigan** [comment]
So then the goal of running close on the connectionManager is to just close all the channels and not the connection itself?

**Comment by jwalton** [comment]
No, it should close the connection to.  I'll patch it tomorrow.  Thanks for
pointing this out.

**Comment by jwalton** [comment]
Published as v1.3.1.
