### ISSUE TITLE
json:true benefits

### ISSUE THREAD

**Issue by zatziky** [benbria/node-amqp-connection-manager#72]
Is there any benefit (like performance) of using `json:true` instead of sending JS object directly?

**Comment by jwalton** [comment]
No.  In our application we exclusively pass JSON around, so it just saves us from having to type `JSON.stringify` and `JSON.parse` everywhere.  :)

**Comment by jwalton** [comment]
Can you send a JSON object directly to amqp?  I don't think that was possible when I wrote this originally.

**Comment by zatziky** [comment]
No, it's still the same. We are also using `JSON.stringify(content)`.
