### ISSUE TITLE
when channel error occur then connection is closed

### ISSUE THREAD

**Issue by resoliwan** [benbria/node-amqp-connection-manager#9]
this is not a node-amqp-connection-manager bug but 

amqplib has bug when channel error occur then connection is closed

(check this issues https://github.com/squaremo/amqp.node/issues/175)

squaremo said just attach error handler at channel and prevent unhanded error bubbled up to the connection

i set up all exchange and queue and send some publish message using channel wrapper 

if exchange dose not exist then error occur and all channel closed!

i don't want to close connection 

i want to the message is rejected or close that only error occurred channel

so could you please add handler at channel and if error occur just reopen that channel..

thank you

**Comment by jwalton** [comment]
You should be able to add an error handler to the channel in the `setupFn`:

````
var channelWrapper = connection.createChannel({
    setup: function(channel) {
        // `channel` here is a regular amqplib `ConfirmChannel`.
        channel.on("error", function(err) {console.log("Uh oh!");}
        return channel.assertQueue('rxQueueName', {durable: true}),
    }
});
````

**Comment by resoliwan** [comment]
thank you
