### ISSUE TITLE
Change ChannelWrapper.publish() signature

### ISSUE THREAD

**Issue by rudnetto** [benbria/node-amqp-connection-manager#96]
Hello, guys.

I'm using amqp-connection-manager in a project together with Typescript.
But there's a little problem on ChannelWrapper creation that I'm unable to make ts-lint stop complaining 😛 

First I create my TX ChannelWrapper:
```code:javascript
this.ChannelTX = this.Connector.createChannel({
  json: true,
  setup: async (channel: any) => Promise.all([
    channel.assertExchange("events", "topic", {durable: true}),
  ]),
});
```

I'm setting `json: true` so I don't have to Buffer the messages, the lib will do it automatically, right?

Then on another part of the code I publish the messages:
```code:javascript
this.ChannelTX.publish("events", "event.foo.bar", { FooID: 'foo', BarID: 'bar' });
```

TS-Lint will give this an error:
`Argument of type '{ FooID: string; BarID: string; }' is not assignable to parameter of type 'Buffer'.   Object literal may only specify known properties, and 'FooID' does not exist in type 'Buffer'.ts(2345)`

This occurs because ChannelWrapper.publish() signature is `publish(exchange: string, routingKey: string, content: Buffer, options?: Options.Publish, callback?: (err: any, ok: Replies.Empty) => void): Promise<void>;`

Maybe it could be changed from `content: Buffer` to `content: Buffer | Object`.

Or there could be 2 different ChannelWrapper signatures, one that accepts `Buffer` and other that accepts `Object` on `content` param. In this case, `AmqpConnectionManager.createChannel()` would have 2 returning types, depending on `json` param value.

**Comment by tstelzer** [comment]
I am having this problem too, but @rudnetto bear in mind, this package is written in JS, the types are defined as part of https://github.com/DefinitelyTyped/DefinitelyTyped and should be fixed there. So technically this issue is not a responsibility of this package :)

**Comment by rudnetto** [comment]
Oops, my bad for not searching on DefinitelyTyped before opening the issue here.

**Comment by tstelzer** [comment]
I created a PR to fix the issue over there, let's see if it goes through :)

**Comment by jwalton** [comment]
I would not at all be opposed to someone converting this whole package to TS either.  :)

**Comment by tstelzer** [comment]
PR was merged.
